showbiz/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .apiviews import *
from rest_framework.routers import DefaultRouter


router=DefaultRouter()
router.register('categorie',CategorieViewset)
router.register('tag',TagViewset)
router.register('article',ArticleViewset)
router.register('commentaire',CommentaireViewset)
router.register('reponse',ReponseViewset)

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:titre_slug>/',views.single_post, name='singpost'),
    path('api/',include('blog.apiurls'))
]

showbiz/showbiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('blog/', include('blog.urls')),
    path('siteConfig/', include('siteConfig.urls')),
    path('admin/filebrowser/', site.urls),
    path('api/',include('apiApp.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

showbiz/templates/includes/break.html
{% extends 'bases/base.html' %}
{% load static %}

{% block content %}
<!-- ticker-news-section
			================================================== -->
            <section class="ticker-news">

                <div class="container">
                    <div class="ticker-news-box">
                        <span class="breaking-news">breaking news</span>
                        <ul id="js-news">
                            <li class="news-item"><span class="time-news">11:36 pm</span>  <a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</a> Donec odio. Quisque volutpat mattis eros... </li>
                            <li class="news-item"><span class="time-news">12:40 pm</span>  <a href="#">Dëshmitarja Abrashi: E kam parë Oliverin në turmë,</a> ndërsa neve na shpëtoi “çika Mille” </li>
                            <li class="news-item"><span class="time-news">11:36 pm</span>  <a href="#">Franca do të bashkëpunojë me Kosovën në fushën e shëndetësisë. </a></li>
                            <li class="news-item"><span class="time-news">01:00 am</span>  <a href="#">DioGuardi, kështu e mbrojti Kosovën në Washington, </a> para serbit Vejvoda </li>
                        </ul>
                    </div>
                </div>
    
            </section>
            <!-- End ticker-news-section -->

{ % endblock content % }

showbiz/templates/includes/random.html
{% extends 'bases/base.html' %}
{% load static %}

{% block content %}

<div class="col-md-3">
    <div class="widget posts-widget">
        <h1>Random Post</h1>

        
        {% for rd   in rand %}
            
       
            
        <ul class="list-posts">
            <li>
                <img src="{{rd.cover.url}}" alt="">
                <div class="post-content">
                    <a href="travel.html">
                    {% for td in rd.tags.all %}
                        {{td}}
                    {% endfor %}
                        </a>
                    <h2><a href="{% url 'blog:singpost' rd.titre_slug %}">{{rd.titre}}. </a></h2>
                    <ul class="post-tags">
                        <li><i class="fa fa-clock-o"></i>{{rd.date_add}}</li>
                    </ul>
                </div>
            </li>
        </ul>
        {% endfor %}
    </div>
</div>

{ % endblock content % }